baseUrl = "https://classroom.googleapis.com/"


SCOPE_CLASSROOM_ANNOUNCEMENTS = "https://www.googleapis.com/auth/classroom.announcements"
SCOPE_CLASSROOM_ANNOUNCEMENTS_READONLY = "https://www.googleapis.com/auth/classroom.announcements.readonly"
SCOPE_CLASSROOM_COURSES = "https://www.googleapis.com/auth/classroom.courses"
SCOPE_CLASSROOM_COURSES_READONLY = "https://www.googleapis.com/auth/classroom.courses.readonly"
SCOPE_CLASSROOM_COURSEWORK_ME = "https://www.googleapis.com/auth/classroom.coursework.me"
SCOPE_CLASSROOM_COURSEWORK_ME_READONLY = "https://www.googleapis.com/auth/classroom.coursework.me.readonly"
SCOPE_CLASSROOM_COURSEWORK_STUDENTS = "https://www.googleapis.com/auth/classroom.coursework.students"
SCOPE_CLASSROOM_COURSEWORK_STUDENTS_READONLY = "https://www.googleapis.com/auth/classroom.coursework.students.readonly"
SCOPE_CLASSROOM_GUARDIANLINKS_ME_READONLY = "https://www.googleapis.com/auth/classroom.guardianlinks.me.readonly"
SCOPE_CLASSROOM_GUARDIANLINKS_STUDENTS = "https://www.googleapis.com/auth/classroom.guardianlinks.students"
SCOPE_CLASSROOM_GUARDIANLINKS_STUDENTS_READONLY = "https://www.googleapis.com/auth/classroom.guardianlinks.students.readonly"
SCOPE_CLASSROOM_PROFILE_EMAILS = "https://www.googleapis.com/auth/classroom.profile.emails"
SCOPE_CLASSROOM_PROFILE_PHOTOS = "https://www.googleapis.com/auth/classroom.profile.photos"
SCOPE_CLASSROOM_PUSH_NOTIFICATIONS = "https://www.googleapis.com/auth/classroom.push-notifications"
SCOPE_CLASSROOM_ROSTERS = "https://www.googleapis.com/auth/classroom.rosters"
SCOPE_CLASSROOM_ROSTERS_READONLY = "https://www.googleapis.com/auth/classroom.rosters.readonly"
SCOPE_CLASSROOM_STUDENT_SUBMISSIONS_ME_READONLY = "https://www.googleapis.com/auth/classroom.student-submissions.me.readonly"
SCOPE_CLASSROOM_STUDENT_SUBMISSIONS_STUDENTS_READONLY = "https://www.googleapis.com/auth/classroom.student-submissions.students.readonly"