baseUrl = "https://script.googleapis.com/"


SCOPE_ = "https://mail.google.com/"
SCOPE_FEEDS = "https://www.google.com/calendar/feeds"
SCOPE_FEEDS = "https://www.google.com/m8/feeds"
SCOPE_ADMIN_DIRECTORY_GROUP = "https://www.googleapis.com/auth/admin.directory.group"
SCOPE_ADMIN_DIRECTORY_USER = "https://www.googleapis.com/auth/admin.directory.user"
SCOPE_DOCUMENTS = "https://www.googleapis.com/auth/documents"
SCOPE_DRIVE = "https://www.googleapis.com/auth/drive"
SCOPE_FORMS = "https://www.googleapis.com/auth/forms"
SCOPE_FORMS_CURRENTONLY = "https://www.googleapis.com/auth/forms.currentonly"
SCOPE_GROUPS = "https://www.googleapis.com/auth/groups"
SCOPE_SPREADSHEETS = "https://www.googleapis.com/auth/spreadsheets"
SCOPE_USERINFO_EMAIL = "https://www.googleapis.com/auth/userinfo.email"