baseUrl = "https://www.googleapis.com/fitness/v1/users/"


SCOPE_FITNESS_ACTIVITY_READ = "https://www.googleapis.com/auth/fitness.activity.read"
SCOPE_FITNESS_ACTIVITY_WRITE = "https://www.googleapis.com/auth/fitness.activity.write"
SCOPE_FITNESS_BLOOD_GLUCOSE_READ = "https://www.googleapis.com/auth/fitness.blood_glucose.read"
SCOPE_FITNESS_BLOOD_GLUCOSE_WRITE = "https://www.googleapis.com/auth/fitness.blood_glucose.write"
SCOPE_FITNESS_BLOOD_PRESSURE_READ = "https://www.googleapis.com/auth/fitness.blood_pressure.read"
SCOPE_FITNESS_BLOOD_PRESSURE_WRITE = "https://www.googleapis.com/auth/fitness.blood_pressure.write"
SCOPE_FITNESS_BODY_READ = "https://www.googleapis.com/auth/fitness.body.read"
SCOPE_FITNESS_BODY_WRITE = "https://www.googleapis.com/auth/fitness.body.write"
SCOPE_FITNESS_BODY_TEMPERATURE_READ = "https://www.googleapis.com/auth/fitness.body_temperature.read"
SCOPE_FITNESS_BODY_TEMPERATURE_WRITE = "https://www.googleapis.com/auth/fitness.body_temperature.write"
SCOPE_FITNESS_LOCATION_READ = "https://www.googleapis.com/auth/fitness.location.read"
SCOPE_FITNESS_LOCATION_WRITE = "https://www.googleapis.com/auth/fitness.location.write"
SCOPE_FITNESS_NUTRITION_READ = "https://www.googleapis.com/auth/fitness.nutrition.read"
SCOPE_FITNESS_NUTRITION_WRITE = "https://www.googleapis.com/auth/fitness.nutrition.write"
SCOPE_FITNESS_OXYGEN_SATURATION_READ = "https://www.googleapis.com/auth/fitness.oxygen_saturation.read"
SCOPE_FITNESS_OXYGEN_SATURATION_WRITE = "https://www.googleapis.com/auth/fitness.oxygen_saturation.write"
SCOPE_FITNESS_REPRODUCTIVE_HEALTH_READ = "https://www.googleapis.com/auth/fitness.reproductive_health.read"
SCOPE_FITNESS_REPRODUCTIVE_HEALTH_WRITE = "https://www.googleapis.com/auth/fitness.reproductive_health.write"